"""initial schema

Revision ID: 09903b6b8081
Revises:
Create Date: 2026-06-10 11:46:12.775868
"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = '09903b6b8081'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('members',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('member_id', sa.String(length=128), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('members', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_members_member_id'), ['member_id'], unique=True)

    op.create_table('risk_cases',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('case_id', sa.String(length=128), nullable=False),
    sa.Column('member_pk', sa.Integer(), nullable=False),
    sa.Column('risk_score', sa.Float(), nullable=False),
    sa.Column('risk_band', sa.String(length=16), nullable=False),
    sa.Column('model_name', sa.String(length=128), nullable=False),
    sa.Column('model_version', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['member_pk'], ['members.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('risk_cases', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_risk_cases_case_id'), ['case_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_risk_cases_member_pk'), ['member_pk'], unique=False)

    op.create_table('explanations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('risk_case_id', sa.Integer(), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('member_explanation', sa.Text(), nullable=False),
    sa.Column('factor_explanations', sa.JSON(), nullable=False),
    sa.Column('limitations', sa.JSON(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('retry_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['risk_case_id'], ['risk_cases.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('explanations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_explanations_risk_case_id'), ['risk_case_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_explanations_status'), ['status'], unique=False)

    op.create_table('risk_factors',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('risk_case_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=256), nullable=False),
    sa.Column('direction', sa.String(length=32), nullable=False),
    sa.Column('weight', sa.Float(), nullable=False),
    sa.Column('evidence', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['risk_case_id'], ['risk_cases.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('risk_factors', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_risk_factors_risk_case_id'), ['risk_case_id'], unique=False)

    op.create_table('audit_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('case_id', sa.String(length=128), nullable=True),
    sa.Column('explanation_id', sa.Integer(), nullable=True),
    sa.Column('event', sa.String(length=64), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['explanation_id'], ['explanations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_audit_logs_case_id'), ['case_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_logs_event'), ['event'], unique=False)

    op.create_table('eval_results',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('explanation_id', sa.Integer(), nullable=False),
    sa.Column('faithfulness_score', sa.Float(), nullable=False),
    sa.Column('coverage_score', sa.Float(), nullable=False),
    sa.Column('readability_score', sa.Float(), nullable=False),
    sa.Column('safety_passed', sa.Boolean(), nullable=False),
    sa.Column('decision', sa.String(length=16), nullable=False),
    sa.Column('details', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['explanation_id'], ['explanations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('eval_results', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_eval_results_explanation_id'), ['explanation_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('eval_results', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_eval_results_explanation_id'))

    op.drop_table('eval_results')
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_audit_logs_event'))
        batch_op.drop_index(batch_op.f('ix_audit_logs_case_id'))

    op.drop_table('audit_logs')
    with op.batch_alter_table('risk_factors', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_risk_factors_risk_case_id'))

    op.drop_table('risk_factors')
    with op.batch_alter_table('explanations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_explanations_status'))
        batch_op.drop_index(batch_op.f('ix_explanations_risk_case_id'))

    op.drop_table('explanations')
    with op.batch_alter_table('risk_cases', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_risk_cases_member_pk'))
        batch_op.drop_index(batch_op.f('ix_risk_cases_case_id'))

    op.drop_table('risk_cases')
    with op.batch_alter_table('members', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_members_member_id'))

    op.drop_table('members')
    # ### end Alembic commands ###
